name: pycaret_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pycaret=3.2
  - streamlit
  - jupyterlab
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - ipykernel
